[package]
name = "curlxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
regex = "1.6"
reqwest = { version = "0.11", features = [] }
tokio = { version = "1", features = ["full"] }
